scene_params_dict = {
    scene_name = "livingroom2"
    window_area_emitter_id_list = [] # need to manually specify in XML: e.g. <emitter type="area" id="lamp_oven_0">
    merge_lamp_id_list = ['lamp_0']  # need to manually specify in XML
}